package io.bizflowframework.biz.flow.ext.runtime.serde;

import io.bizflowframework.biz.flow.ext.runtime.AggregateRoot;
import io.bizflowframework.biz.flow.ext.runtime.event.AggregateRootEventPayload;

public interface AggregateRootEventPayloadSerde<T extends AggregateRoot<?, T>, P extends AggregateRootEventPayload<T>> {
    SerializedEventPayload serialize(P selfAggregateRootEventPayload);

    P deserialize(SerializedEventPayload serializedEventPayload);

    default Class<T> aggregateRootClass() {
        throw new RuntimeException("Do not implement. Will be generated by extension :)");
    }

    default Class<P> aggregateRootEventPayloadClass() {
        throw new RuntimeException("Do not implement. Will be generated by extension :)");
    }
}